"""
ingestion/pipelines/init_db.py
--------------------------------
One-time (idempotent) database bootstrap for the pgvector store.

WHY THIS FILE EXISTS:
  Before the first ingestion run, the database needs the pgvector extension,
  the chunks table, and vector + metadata indexes. This script creates them
  idempotently (IF NOT EXISTS), so running it twice is safe.

RUN:
  make db-init

CONNECTION STRATEGY — Cloud SQL Python Connector, ip_type="PUBLIC":
  We connect via the Cloud SQL Python Connector with ip_type="PUBLIC". This
  is required from outside GCP's VPC (e.g. a developer's laptop) — a private-
  IP-only instance is unreachable from any machine not inside the VPC.
  The Connector uses the public IP purely as a routable address for its own
  IAM-authenticated, encrypted tunnel; authorized-networks is empty so no
  raw TCP connection is possible from anywhere.
  On Cloud Run (inside the VPC), ip_type can switch to "PRIVATE".
  See BUG_FIX_LOG.md "Init DB: private-IP-only Cloud SQL unreachable from laptop".

WHAT IT CREATES:
  CREATE EXTENSION IF NOT EXISTS vector;

  CREATE TABLE IF NOT EXISTS chunks (
      chunk_id            text PRIMARY KEY,
      text                text NOT NULL,
      embedding           vector(768) NOT NULL,
      course_name         text NOT NULL,
      subject             text NOT NULL,
      chapter             text NOT NULL,
      topic               text,
      page_number         integer NOT NULL,
      page_range          text,
      source_type         text NOT NULL,
      document_version    text NOT NULL,
      ingestion_date      date NOT NULL,
      chunk_index_in_doc  integer,
      char_count          integer
  );

  CREATE INDEX IF NOT EXISTS chunks_embedding_hnsw
      ON chunks USING hnsw (embedding vector_cosine_ops);

  CREATE INDEX IF NOT EXISTS chunks_course_chapter
      ON chunks (course_name, chapter);   -- speeds up metadata filters

WHY HNSW AND NOT IVFFLAT:
  pgvector supports two ANN index types: IVFFlat (needs representative data
  to build well, accuracy degrades as data is added) and HNSW (builds
  incrementally, no pre-existing-data requirement, generally better recall).
  Since we build the index BEFORE any data exists, HNSW is the correct choice
  — IVFFlat would build a poor-quality index on an empty table and need a
  REINDEX later.

WHY chunk_id IS text, NOT a database-generated serial/uuid:
  chunk_id is generated by the chunker (Module 2, uuid4().hex[:12]) at
  chunk-creation time, before the row ever reaches the database. This lets the
  ingestion pipeline log a chunk's ID immediately after chunking, before it's
  written to Postgres at all — useful for debugging a failed batch upsert.

# Interview notes: local-notes/INTERVIEW_PREP.md — "ingestion/pipelines/init_db.py"
"""

import sqlalchemy
from google.cloud.sql.connector import Connector

from app.core.config import settings
from app.core.logging import get_logger, setup_logging

logger = get_logger(__name__)


# All DDL executed in order by run_ddl(). Each statement is idempotent
# (IF NOT EXISTS) so re-running after a partial failure is always safe.
DDL_STATEMENTS = [
    "CREATE EXTENSION IF NOT EXISTS vector;",
    """
    CREATE TABLE IF NOT EXISTS chunks (
        chunk_id            text PRIMARY KEY,
        text                text NOT NULL,
        embedding           vector(768) NOT NULL,
        course_name         text NOT NULL,
        subject             text NOT NULL,
        chapter             text NOT NULL,
        topic               text,
        page_number         integer NOT NULL,
        page_range          text,
        source_type         text NOT NULL,
        document_version    text NOT NULL,
        ingestion_date      date NOT NULL,
        chunk_index_in_doc  integer,
        char_count          integer
    );
    """,
    # HNSW index for approximate-nearest-neighbour cosine similarity search.
    "CREATE INDEX IF NOT EXISTS chunks_embedding_hnsw ON chunks USING hnsw (embedding vector_cosine_ops);",
    # Composite B-tree index for fast metadata filtering in similarity_search_with_score().
    "CREATE INDEX IF NOT EXISTS chunks_course_chapter ON chunks (course_name, chapter);",
]


def get_engine(ip_type: str = "PUBLIC") -> sqlalchemy.engine.Engine:
    """
    Build a SQLAlchemy engine that connects to cognara-pg via the Cloud SQL
    Python Connector. IAM-authenticated via Application Default Credentials —
    never a raw unauthenticated socket.

    ip_type="PUBLIC" (default): required from outside the VPC (developer's
    laptop). Uses the instance's public IP as a routable address for the
    Connector's own encrypted tunnel; authorized-networks is empty so no
    other client can connect that way.
    See BUG_FIX_LOG.md "Init DB: private-IP-only Cloud SQL unreachable from laptop".

    ip_type="PRIVATE": for use from inside the VPC only (e.g. Cloud Run).
    Raises a connection error if attempted from outside the VPC.
    """
    connector = Connector()

    def getconn():
        # pg8000 is the pure-Python Postgres driver the Connector supports;
        # no native libpq dependency required.
        return connector.connect(
            settings.CLOUD_SQL_INSTANCE,
            "pg8000",
            user=settings.PGVECTOR_USER,
            password=settings.PGVECTOR_PASSWORD,
            db=settings.PGVECTOR_DB,
            ip_type=ip_type,
        )

    # The "postgresql+pg8000://" URL is a placeholder — the actual connection
    # is always provided by the creator= callable above, not the URL.
    engine = sqlalchemy.create_engine("postgresql+pg8000://", creator=getconn)
    return engine


def run_ddl(engine: sqlalchemy.engine.Engine) -> None:
    """Run every DDL statement in order, each in its own committed transaction."""
    with engine.connect() as conn:
        for statement in DDL_STATEMENTS:
            logger.info("running_ddl", statement_preview=statement.strip().splitlines()[0])
            conn.execute(sqlalchemy.text(statement))
            # Commit after each statement so a partial failure leaves previous
            # statements applied (extension and table exist even if index fails).
            conn.commit()


def verify_schema(engine: sqlalchemy.engine.Engine) -> dict:
    """
    Read back what actually exists after running the DDL, so `make db-init`
    reports real, verified state rather than just "no errors were raised".

    Returns a dict summary used for the printed report.
    """
    with engine.connect() as conn:
        # Check the pgvector extension is installed and get its version.
        extension_row = conn.execute(sqlalchemy.text(
            "SELECT extname, extversion FROM pg_extension WHERE extname = 'vector';"
        )).fetchone()

        # Confirm the chunks table exists in the public schema.
        table_exists = conn.execute(sqlalchemy.text(
            "SELECT EXISTS (SELECT FROM information_schema.tables "
            "WHERE table_name = 'chunks');"
        )).scalar()

        # List all indexes on the chunks table (verifies both HNSW and B-tree
        # indexes were created successfully).
        index_rows = conn.execute(sqlalchemy.text(
            "SELECT indexname FROM pg_indexes WHERE tablename = 'chunks';"
        )).fetchall()

        # Current row count — expected to be 0 on a fresh bootstrap, > 0
        # if re-run after ingestion.
        row_count = conn.execute(sqlalchemy.text("SELECT COUNT(*) FROM chunks;")).scalar()

    return {
        "pgvector_installed":  extension_row is not None,
        "pgvector_version":    extension_row[1] if extension_row else None,
        "chunks_table_exists": bool(table_exists),
        "indexes":             sorted(r[0] for r in index_rows),
        "row_count":           row_count,
    }


def main() -> None:
    """Create extension, chunks table, and indexes. Idempotent. Verifies and reports."""
    setup_logging()
    logger.info("init_db_start", instance=settings.CLOUD_SQL_INSTANCE, database=settings.PGVECTOR_DB)

    engine = get_engine(ip_type="PUBLIC")
    try:
        run_ddl(engine)
        summary = verify_schema(engine)
    finally:
        # Dispose all connections in the pool before exiting.
        engine.dispose()

    logger.info("init_db_done", **summary)

    print("\n=== Cognara DB schema bootstrap complete ===")
    print(f"pgvector extension installed : {summary['pgvector_installed']} (v{summary['pgvector_version']})")
    print(f"chunks table exists          : {summary['chunks_table_exists']}")
    print(f"indexes on chunks            : {', '.join(summary['indexes'])}")
    print(f"current row count            : {summary['row_count']}")
    print()


if __name__ == "__main__":
    main()
