"""
ingestion/pipelines/init_db.py
--------------------------------
One-time (idempotent) database bootstrap for the pgvector store AND
Layer 5's stateful learning-mode session tables.

WHY THIS FILE EXISTS:
  Before the first ingestion run, the database needs the pgvector extension,
  the chunks table, and vector + metadata indexes. This script creates them
  idempotently (IF NOT EXISTS), so running it twice is safe. It also creates
  the learning_sessions / learning_session_turns tables Quiz and Interview
  mode need (see ADR 0009) — added to this SAME bootstrap script rather than
  a separate one, since both are one-time, idempotent Cloud SQL schema setup
  for the same database.

RUN:
  make db-init

CONNECTION STRATEGY — Cloud SQL Python Connector, ip_type="PUBLIC":
  We connect via the Cloud SQL Python Connector with ip_type="PUBLIC". This
  is required from outside GCP's VPC (e.g. a developer's laptop) — a private-
  IP-only instance is unreachable from any machine not inside the VPC.
  The Connector uses the public IP purely as a routable address for its own
  IAM-authenticated, encrypted tunnel; authorized-networks is empty so no
  raw TCP connection is possible from anywhere.
  On Cloud Run (inside the VPC), ip_type can switch to "PRIVATE".
  See BUG_FIX_LOG.md "Init DB: private-IP-only Cloud SQL unreachable from laptop".

WHAT IT CREATES (chunks table — Layers 1-4):
  CREATE EXTENSION IF NOT EXISTS vector;
  CREATE TABLE IF NOT EXISTS chunks (...)          -- see DDL_STATEMENTS
  CREATE INDEX IF NOT EXISTS chunks_embedding_hnsw ...
  CREATE INDEX IF NOT EXISTS chunks_course_chapter ...

WHAT IT CREATES (learning_sessions / learning_session_turns — Layer 5,
Quiz + Interview modes, see ADR 0009):
  ONE shared schema for BOTH modes, distinguished by the `mode` column —
  not two separate tables, since both modes need the identical shape of
  state (an ordered sequence of question/evidence/answer/correctness
  turns within a session). See ADR 0009 for the full reasoning.

  CREATE TABLE IF NOT EXISTS learning_sessions (
      session_id   text PRIMARY KEY,
      mode         text NOT NULL,        -- 'quiz' | 'interview'
      topic        text NOT NULL,
      course_filter text,
      status       text NOT NULL DEFAULT 'active',  -- 'active' | 'completed'
      created_at   timestamptz NOT NULL DEFAULT now()
  );

  CREATE TABLE IF NOT EXISTS learning_session_turns (
      turn_id            text PRIMARY KEY,
      session_id         text NOT NULL REFERENCES learning_sessions(session_id),
      turn_number        integer NOT NULL,
      question_text      text NOT NULL,
      answer_key_text    text NOT NULL,    -- internal grading reference, never shown to the user
      user_answer_text   text,             -- NULL until the user actually answers
      is_correct         boolean,          -- NULL until graded
      feedback_text      text,             -- NULL until graded
      evidence_chunk_ids jsonb NOT NULL,   -- which chunk_ids this question was grounded in
      created_at         timestamptz NOT NULL DEFAULT now()
  );

WHY HNSW AND NOT IVFFLAT:
  pgvector supports two ANN index types: IVFFlat (needs representative data
  to build well, accuracy degrades as data is added) and HNSW (builds
  incrementally, no pre-existing-data requirement, generally better recall).
  Since we build the index BEFORE any data exists, HNSW is the correct choice
  — IVFFlat would build a poor-quality index on an empty table and need a
  REINDEX later.

WHY chunk_id / session_id / turn_id ARE text, NOT a database-generated
serial/uuid:
  Each is generated by application code (uuid4().hex) at creation time,
  before the row ever reaches the database. This lets calling code log an
  ID immediately after creation, before it's written to Postgres at all —
  useful for debugging a failed batch write.

# Interview notes: local-notes/INTERVIEW_PREP.md — "ingestion/pipelines/init_db.py"
"""

import sqlalchemy
from google.cloud.sql.connector import Connector

from app.core.config import settings
from app.core.logging import get_logger, setup_logging

logger = get_logger(__name__)


# All DDL executed in order by run_ddl(). Each statement is idempotent
# (IF NOT EXISTS) so re-running after a partial failure is always safe.
DDL_STATEMENTS = [
    "CREATE EXTENSION IF NOT EXISTS vector;",
    """
    CREATE TABLE IF NOT EXISTS chunks (
        chunk_id            text PRIMARY KEY,
        text                text NOT NULL,
        embedding           vector(768) NOT NULL,
        course_name         text NOT NULL,
        subject             text NOT NULL,
        chapter             text NOT NULL,
        topic               text,
        page_number         integer NOT NULL,
        page_range          text,
        source_type         text NOT NULL,
        document_version    text NOT NULL,
        ingestion_date      date NOT NULL,
        chunk_index_in_doc  integer,
        char_count          integer
    );
    """,
    # HNSW index for approximate-nearest-neighbour cosine similarity search.
    "CREATE INDEX IF NOT EXISTS chunks_embedding_hnsw ON chunks USING hnsw (embedding vector_cosine_ops);",
    # Composite B-tree index for fast metadata filtering in similarity_search_with_score().
    "CREATE INDEX IF NOT EXISTS chunks_course_chapter ON chunks (course_name, chapter);",

    # ── Layer 5: Quiz + Interview session tables (see ADR 0009) ─────────────
    """
    CREATE TABLE IF NOT EXISTS learning_sessions (
        session_id    text PRIMARY KEY,
        mode          text NOT NULL,
        topic         text NOT NULL,
        course_filter text,
        status        text NOT NULL DEFAULT 'active',
        created_at    timestamptz NOT NULL DEFAULT now()
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS learning_session_turns (
        turn_id            text PRIMARY KEY,
        session_id         text NOT NULL REFERENCES learning_sessions(session_id),
        turn_number        integer NOT NULL,
        question_text      text NOT NULL,
        answer_key_text    text NOT NULL,
        user_answer_text   text,
        is_correct         boolean,
        feedback_text      text,
        evidence_chunk_ids jsonb NOT NULL,
        created_at         timestamptz NOT NULL DEFAULT now()
    );
    """,
    # Speeds up "give me all turns for this session, in order" — the core
    # query both Quiz and Interview mode run on every turn.
    "CREATE INDEX IF NOT EXISTS session_turns_session_id ON learning_session_turns (session_id, turn_number);",
]


def get_engine(ip_type: str = "PUBLIC") -> sqlalchemy.engine.Engine:
    """
    Build a SQLAlchemy engine that connects to cognara-pg via the Cloud SQL
    Python Connector. IAM-authenticated via Application Default Credentials —
    never a raw unauthenticated socket.

    ip_type="PUBLIC" (default): required from outside the VPC (developer's
    laptop). Uses the instance's public IP as a routable address for the
    Connector's own encrypted tunnel; authorized-networks is empty so no
    other client can connect that way.
    See BUG_FIX_LOG.md "Init DB: private-IP-only Cloud SQL unreachable from laptop".

    ip_type="PRIVATE": for use from inside the VPC only (e.g. Cloud Run).
    Raises a connection error if attempted from outside the VPC.
    """
    connector = Connector()

    def getconn():
        # pg8000 is the pure-Python Postgres driver the Connector supports;
        # no native libpq dependency required.
        return connector.connect(
            settings.CLOUD_SQL_INSTANCE,
            "pg8000",
            user=settings.PGVECTOR_USER,
            password=settings.PGVECTOR_PASSWORD,
            db=settings.PGVECTOR_DB,
            ip_type=ip_type,
        )

    # The "postgresql+pg8000://" URL is a placeholder — the actual connection
    # is always provided by the creator= callable above, not the URL.
    engine = sqlalchemy.create_engine("postgresql+pg8000://", creator=getconn)
    return engine


def run_ddl(engine: sqlalchemy.engine.Engine) -> None:
    """Run every DDL statement in order, each in its own committed transaction."""
    with engine.connect() as conn:
        for statement in DDL_STATEMENTS:
            logger.info("running_ddl", statement_preview=statement.strip().splitlines()[0])
            conn.execute(sqlalchemy.text(statement))
            # Commit after each statement so a partial failure leaves previous
            # statements applied (extension and table exist even if index fails).
            conn.commit()


def verify_schema(engine: sqlalchemy.engine.Engine) -> dict:
    """
    Read back what actually exists after running the DDL, so `make db-init`
    reports real, verified state rather than just "no errors were raised".

    Returns a dict summary used for the printed report.
    """
    with engine.connect() as conn:
        # Check the pgvector extension is installed and get its version.
        extension_row = conn.execute(sqlalchemy.text(
            "SELECT extname, extversion FROM pg_extension WHERE extname = 'vector';"
        )).fetchone()

        # Confirm the chunks table exists in the public schema.
        table_exists = conn.execute(sqlalchemy.text(
            "SELECT EXISTS (SELECT FROM information_schema.tables "
            "WHERE table_name = 'chunks');"
        )).scalar()

        # List all indexes on the chunks table (verifies both HNSW and B-tree
        # indexes were created successfully).
        index_rows = conn.execute(sqlalchemy.text(
            "SELECT indexname FROM pg_indexes WHERE tablename = 'chunks';"
        )).fetchall()

        # Current row count — expected to be 0 on a fresh bootstrap, > 0
        # if re-run after ingestion.
        row_count = conn.execute(sqlalchemy.text("SELECT COUNT(*) FROM chunks;")).scalar()

        # Confirm the two new Layer 5 session tables exist as well.
        sessions_table_exists = conn.execute(sqlalchemy.text(
            "SELECT EXISTS (SELECT FROM information_schema.tables "
            "WHERE table_name = 'learning_sessions');"
        )).scalar()
        turns_table_exists = conn.execute(sqlalchemy.text(
            "SELECT EXISTS (SELECT FROM information_schema.tables "
            "WHERE table_name = 'learning_session_turns');"
        )).scalar()

    return {
        "pgvector_installed":       extension_row is not None,
        "pgvector_version":         extension_row[1] if extension_row else None,
        "chunks_table_exists":      bool(table_exists),
        "indexes":                  sorted(r[0] for r in index_rows),
        "row_count":                row_count,
        "learning_sessions_exists": bool(sessions_table_exists),
        "session_turns_exists":     bool(turns_table_exists),
    }


def main() -> None:
    """Create extension, chunks table, session tables, and indexes. Idempotent. Verifies and reports."""
    setup_logging()
    logger.info("init_db_start", instance=settings.CLOUD_SQL_INSTANCE, database=settings.PGVECTOR_DB)

    engine = get_engine(ip_type="PUBLIC")
    try:
        run_ddl(engine)
        summary = verify_schema(engine)
    finally:
        # Dispose all connections in the pool before exiting.
        engine.dispose()

    logger.info("init_db_done", **summary)

    print("\n=== Cognara DB schema bootstrap complete ===")
    print(f"pgvector extension installed : {summary['pgvector_installed']} (v{summary['pgvector_version']})")
    print(f"chunks table exists          : {summary['chunks_table_exists']}")
    print(f"indexes on chunks            : {', '.join(summary['indexes'])}")
    print(f"current row count            : {summary['row_count']}")
    print(f"learning_sessions exists     : {summary['learning_sessions_exists']}")
    print(f"learning_session_turns exists: {summary['session_turns_exists']}")
    print()


if __name__ == "__main__":
    main()
