"""
ingestion/pipelines/init_db.py
------------------------------
One-time database bootstrap for the pgvector store.

WHY THIS FILE EXISTS:
  Before the first ingestion run, the database needs the pgvector extension,
  the chunks table, and a vector index. This script creates them idempotently
  (IF NOT EXISTS), so running it twice is safe.

RUN:
  make db-init

CONNECTION STRATEGY — Cloud SQL Python Connector, ip_type="PUBLIC":
  This connection strategy went through a real correction while building
  this module, worth understanding because it's a genuine GCP networking
  lesson, not just a config detail.

  ATTEMPT 1 (failed): cognara-pg was originally provisioned with
  --no-assign-ip (private IP only, see ADR 0003). The plan was to connect
  via the Cloud SQL Python Connector with ip_type="PRIVATE" — no separate
  proxy process, works locally AND on Cloud Run with the same code path.
  This failed with a raw socket ConnectionRefusedError. Root cause: for a
  PRIVATE-IP instance, the Connector (and the standalone Auth Proxy
  binary, equally) must run on a machine that is network-adjacent to the
  instance's VPC — a GCE VM, a Cloud Run instance, anything actually
  inside or peered with the VPC. A laptop on a home network is not
  network-adjacent to any GCP VPC, proxy or no proxy, Connector or no
  Connector. This is a hard requirement, not a missing flag.

  FIX: cognara-pg was patched to also have a PUBLIC IP
  (`gcloud sql instances patch --assign-ip`), with authorized-networks
  left EMPTY — meaning no raw IP-based connection is possible from
  anywhere, including this machine's real IP. The Connector, given
  ip_type="PUBLIC", uses the public IP purely as a routable address to
  open its own IAM-authenticated, encrypted tunnel — it is not a plain
  TCP connection with a password, and no inbound firewall rule had to be
  opened. This is the standard "public IP, but zero authorized networks,
  Connector/Proxy-only access" pattern GCP itself recommends for exactly
  this situation (local development against a Cloud SQL instance).

  On Cloud Run later, ip_type can switch back to "PRIVATE", since Cloud
  Run instances genuinely are attached to the VPC — the public IP stays
  provisioned (harmless, since nothing is authorized to use it directly)
  but production traffic never needs it.

WHAT IT CREATES:
  CREATE EXTENSION IF NOT EXISTS vector;

  CREATE TABLE IF NOT EXISTS chunks (
      chunk_id            text PRIMARY KEY,
      text                text NOT NULL,
      embedding           vector(768) NOT NULL,
      course_name         text NOT NULL,
      subject             text NOT NULL,
      chapter             text NOT NULL,
      topic               text,
      page_number         integer NOT NULL,
      page_range          text,
      source_type         text NOT NULL,
      document_version    text NOT NULL,
      ingestion_date      date NOT NULL,
      chunk_index_in_doc  integer,
      char_count          integer
  );

  CREATE INDEX IF NOT EXISTS chunks_embedding_hnsw
      ON chunks USING hnsw (embedding vector_cosine_ops);

  CREATE INDEX IF NOT EXISTS chunks_course_chapter
      ON chunks (course_name, chapter);   -- speeds up metadata filters

WHY HNSW AND NOT IVFFLAT:
  pgvector supports two approximate-nearest-neighbour index types: IVFFlat
  (older, needs a representative sample of data before it builds well, and
  its accuracy degrades as data is added afterward) and HNSW (newer, builds
  incrementally, no pre-existing-data requirement, generally better recall
  at similar speed). Since we're building the index BEFORE any data exists
  — a genuinely empty table — HNSW is the correct choice; IVFFlat would
  actually build a poor-quality index on an empty table and need a REINDEX
  later. We build the table AND its indexes together, before ingestion
  writes a single row, which is why this choice matters here specifically.

WHY chunk_id IS text, NOT a database-generated serial/uuid:
  chunk_id is generated by the chunker (Module 2, uuid4().hex[:12]) at
  chunk-creation time, before the row ever reaches the database. This
  lets the ingestion pipeline log a chunk's ID immediately after chunking,
  before it's written to Postgres at all — useful for debugging a failed
  batch upsert without needing to query the DB to find out which chunk_id
  belongs to which text.

INTERVIEW EXPLANATION:
  "Schema bootstrap is a separate, idempotent step — not something the
  ingestion pipeline does implicitly. I use HNSW rather than IVFFlat
  because we're indexing an empty table before any data exists — IVFFlat
  needs representative data to build a good index, HNSW doesn't. I
  connect via the Cloud SQL Python Connector so the exact same connection
  code path runs locally and on Cloud Run. I initially tried a fully
  private-IP instance with no public address at all, which is the more
  locked-down option, but learned that a private-IP-only instance is
  unreachable from any machine that isn't already inside the VPC —
  including a developer's laptop. I added a public IP back with zero
  authorized networks, so the only way in is still the Connector's
  IAM-authenticated tunnel, not a raw password-only connection — that's
  the right balance between security and an actually-usable local dev
  loop."
"""

import sqlalchemy
from google.cloud.sql.connector import Connector

from app.core.config import settings
from app.core.logging import get_logger, setup_logging

logger = get_logger(__name__)


DDL_STATEMENTS = [
    "CREATE EXTENSION IF NOT EXISTS vector;",
    """
    CREATE TABLE IF NOT EXISTS chunks (
        chunk_id            text PRIMARY KEY,
        text                text NOT NULL,
        embedding           vector(768) NOT NULL,
        course_name         text NOT NULL,
        subject             text NOT NULL,
        chapter             text NOT NULL,
        topic               text,
        page_number         integer NOT NULL,
        page_range          text,
        source_type         text NOT NULL,
        document_version    text NOT NULL,
        ingestion_date      date NOT NULL,
        chunk_index_in_doc  integer,
        char_count          integer
    );
    """,
    "CREATE INDEX IF NOT EXISTS chunks_embedding_hnsw ON chunks USING hnsw (embedding vector_cosine_ops);",
    "CREATE INDEX IF NOT EXISTS chunks_course_chapter ON chunks (course_name, chapter);",
]


def get_engine(ip_type: str = "PUBLIC") -> sqlalchemy.engine.Engine:
    """
    Build a SQLAlchemy engine that connects to cognara-pg via the Cloud
    SQL Python Connector. IAM-authenticated under the hood using
    Application Default Credentials — never a raw unauthenticated socket,
    regardless of which ip_type is used.

    ip_type="PUBLIC" (the default): required for any machine outside the
    VPC — this developer's laptop, for instance. Uses the instance's
    public IP purely as a routable address for the Connector's own
    encrypted tunnel; authorized-networks is empty, so no other client
    can connect that way.

    ip_type="PRIVATE": for use from inside the VPC only (e.g. Cloud Run).
    Will raise a connection error if attempted from outside the VPC —
    see the module docstring for why.
    """
    connector = Connector()

    def getconn():
        return connector.connect(
            settings.CLOUD_SQL_INSTANCE,
            "pg8000",
            user=settings.PGVECTOR_USER,
            password=settings.PGVECTOR_PASSWORD,
            db=settings.PGVECTOR_DB,
            ip_type=ip_type,
        )

    engine = sqlalchemy.create_engine("postgresql+pg8000://", creator=getconn)
    return engine


def run_ddl(engine: sqlalchemy.engine.Engine) -> None:
    """Run every DDL statement in order, inside its own committed transaction."""
    with engine.connect() as conn:
        for statement in DDL_STATEMENTS:
            logger.info("running_ddl", statement_preview=statement.strip().splitlines()[0])
            conn.execute(sqlalchemy.text(statement))
            conn.commit()


def verify_schema(engine: sqlalchemy.engine.Engine) -> dict:
    """
    Read back what actually exists after running the DDL, so `make db-init`
    reports real, verified state rather than just 'no errors were raised'.
    Returns a small dict summary used for the printed report.
    """
    with engine.connect() as conn:
        extension_row = conn.execute(sqlalchemy.text(
            "SELECT extname, extversion FROM pg_extension WHERE extname = 'vector';"
        )).fetchone()

        table_exists = conn.execute(sqlalchemy.text(
            "SELECT EXISTS (SELECT FROM information_schema.tables "
            "WHERE table_name = 'chunks');"
        )).scalar()

        index_rows = conn.execute(sqlalchemy.text(
            "SELECT indexname FROM pg_indexes WHERE tablename = 'chunks';"
        )).fetchall()

        row_count = conn.execute(sqlalchemy.text("SELECT COUNT(*) FROM chunks;")).scalar()

    return {
        "pgvector_installed": extension_row is not None,
        "pgvector_version": extension_row[1] if extension_row else None,
        "chunks_table_exists": bool(table_exists),
        "indexes": sorted(r[0] for r in index_rows),
        "row_count": row_count,
    }


def main() -> None:
    """Create extension, chunks table, and indexes. Idempotent. Verifies and reports."""
    setup_logging()
    logger.info("init_db_start", instance=settings.CLOUD_SQL_INSTANCE, database=settings.PGVECTOR_DB)

    engine = get_engine(ip_type="PUBLIC")
    try:
        run_ddl(engine)
        summary = verify_schema(engine)
    finally:
        engine.dispose()

    logger.info("init_db_done", **summary)

    print("\n=== Cognara DB schema bootstrap complete ===")
    print(f"pgvector extension installed : {summary['pgvector_installed']} (v{summary['pgvector_version']})")
    print(f"chunks table exists          : {summary['chunks_table_exists']}")
    print(f"indexes on chunks            : {', '.join(summary['indexes'])}")
    print(f"current row count            : {summary['row_count']}")
    print()


if __name__ == "__main__":
    main()
